services:
  postgres:
    image: postgres:15-alpine
    container_name: building_qr_db
    environment:
      POSTGRES_DB: qr_code_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - building_qr_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d qr_code_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: building_qr_app
    ports:
      - "8022:8002"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/qr_code_db
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs

volumes:
  building_qr_postgres_data:
